/**
 * Get the canonical site URL.
 * 
 * Priority:
 * 1. NEXT_PUBLIC_SITE_URL (Env Var - Required for Prod)
 * 2. VERCEL_URL (Auto-generated by Vercel)
 * 3. localhost:3000 (Fallback)
 */
export function getSiteUrl(): string {
    let url = process.env.NEXT_PUBLIC_SITE_URL ||
        process.env.NEXT_PUBLIC_VERCEL_URL ||
        'http://localhost:3000';

    // Ensure protocol
    if (!url.startsWith('http')) {
        url = `https://${url}`;
    }

    // Remove trailing slash
    if (url.endsWith('/')) {
        url = url.slice(0, -1);
    }

    return url;
}
